# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import winsdk.system

_ns_module = winsdk.system._import_ns_module("Windows.Data.Xml.Xsl")

try:
    import winsdk.windows.data.xml.dom
except ImportError:
    pass


XsltProcessor = _ns_module.XsltProcessor
