# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import datetime
import sys
import types
import typing

import winsdk.system

Self = typing.TypeVar('Self')

class HtmlUtilities(winsdk.system.Object):
    @staticmethod
    def _from(obj: winsdk.system.Object) -> HtmlUtilities: ...
    @staticmethod
    def convert_to_text(html: str) -> str: ...

