# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import winsdk.system

_ns_module = winsdk.system._import_ns_module("Windows.Phone.System")


SystemProtection = _ns_module.SystemProtection
