# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import winsdk.system

_ns_module = winsdk.system._import_ns_module("Windows.Phone.UI.Input")

try:
    import winsdk.windows.foundation
except ImportError:
    pass


BackPressedEventArgs = _ns_module.BackPressedEventArgs
CameraEventArgs = _ns_module.CameraEventArgs
HardwareButtons = _ns_module.HardwareButtons
