# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import datetime
import sys
import types
import typing

import winsdk.system

Self = typing.TypeVar('Self')

class RetailMode(winsdk.system.Object):
    retail_mode_enabled: typing.ClassVar[winsdk.system.Boolean]
    @staticmethod
    def _from(obj: winsdk.system.Object) -> RetailMode: ...

