# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import winsdk.system

_ns_module = winsdk.system._import_ns_module("Windows.Perception.Spatial.Preview")

try:
    import winsdk.windows.foundation.numerics
except ImportError:
    pass

try:
    import winsdk.windows.perception.spatial
except ImportError:
    pass


SpatialGraphInteropFrameOfReferencePreview = _ns_module.SpatialGraphInteropFrameOfReferencePreview
SpatialGraphInteropPreview = _ns_module.SpatialGraphInteropPreview
