# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import datetime
import sys
import types
import typing

import winsdk.system
import winsdk.windows.foundation

Self = typing.TypeVar('Self')

class VibrationDevice(winsdk.system.Object):
    @staticmethod
    def _from(obj: winsdk.system.Object) -> VibrationDevice: ...
    def cancel(self) -> None: ...
    @staticmethod
    def get_default() -> typing.Optional[VibrationDevice]: ...
    def vibrate(self, duration: datetime.timedelta) -> None: ...

